### ISSUE TITLE
Misleading labels error

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1056]
The attached script gives this output:

```
# ./test-indom.py mem.util.free
([4294967295], [None])
Traceback (most recent call last):
  File "./test-indom.py", line 15, in <module>
    print(ctx.pmGetInstancesLabels(desc.contents.indom))
  File "/usr/lib64/python3.7/site-packages/pcp/pmapi.py", line 2144, in pmGetInstancesLabels
    raise pmErr(status)
pcp.pmapi.pmErr: PM_ERR_NOAGENT No PMCD agent for domain of request
```

I think "No PMCD for domain of request" is misleading given the situation here.

[test-indom.py.txt](https://github.com/performancecopilot/pcp/files/5239460/test-indom.py.txt)

Thanks.

**Comment by goodwinos** [comment]
Hi Marko, agree the exception is a little obscure. I have a faily simple patch, which I'll commit for pcp-5.2.1 (after a bit of QA). Here's the new output of your test program on two different metrics (one with an indom and one singular) :

```
$ ./test-indom.py hinv.cpu.clock
([0, 1, 2, 3, 4, 5, 6, 7], ['cpu0', 'cpu1', 'cpu2', 'cpu3', 'cpu4', 'cpu5', 'cpu6', 'cpu7'])
{0: {'cpu': 0}, 1: {'cpu': 1}, 2: {'cpu': 2}, 3: {'cpu': 3}, 4: {'cpu': 4}, 5: {'cpu': 5}, 6: {'cpu': 6}, 7: {'cpu': 7}}
{'device_type': 'cpu', 'indom_name': 'per cpu'}

$ ./test-indom.py mem.util.free
([4294967295], [None])
{}
{}
```
