### ISSUE TITLE
pcp-mpstat crashes for metrics recorded once in the archive 

### ISSUE THREAD

**Issue by orasagar** [performancecopilot/pcp#1740]
It has been observed that pcp-mpstat utility crashes with "IndexError: list index out of range" often .We have observed that this happens when pcp-mpstat is used to examine an archive which logs machine info related metrics only once such as 'kernel.uname.sysname' ,'hinv.ncpu' and so on. 

Traceback (most recent call last):
  File "/usr/libexec/pcp/bin/pcp-mpstat", line 676, in <module>
    sts = manager.run()
  File "/usr/lib64/python3.6/site-packages/pcp/pmcc.py", line 687, in run
    self._printer.report(self)
  File "/usr/libexec/pcp/bin/pcp-mpstat", line 629, in report
    self.print_machine_info(group, manager)
  File "/usr/libexec/pcp/bin/pcp-mpstat", line 611, in print_machine_info
    header_string += group['kernel.uname.sysname'].netValues[0][2] + '  '
IndexError: list index out of range

**Comment by natoscott** [comment]
@orasagar I've opened PR #1741 to address this - could you take a look?  Thanks!
