### ISSUE TITLE
pcp-ps regression

### ISSUE THREAD

**Issue by kmcdonell** [performancecopilot/pcp#2081]
qa/1987 is failing all over the country side ... output mismatching (sorting?) and python errors like this one
```
Traceback (most recent call last):
  File "/usr/lib/pcp/bin/pcp-ps", line 771, in <module>
    sts = manager.run()
  File "/usr/lib/python3/dist-packages/pcp/pmcc.py", line 687, in run
    self._printer.report(self)
  File "/usr/lib/pcp/bin/pcp-ps", line 612, in report
    self.__print_report(timestamp, header_indentation, value_indentation, interval_in_seconds)
  File "/usr/lib/pcp/bin/pcp-ps", line 571, in __print_report
    report.print_report(timestamp, header_indentation, value_indentation)
  File "/usr/lib/pcp/bin/pcp-ps", line 519, in print_report
    process.tty_name(), process.s_name(), process.total_time(), process.start(),
  File "/usr/lib/pcp/bin/pcp-ps", line 298, in start
    group = self.manager['psstat']
KeyError: 'psstat'
```

**Comment by kmcdonell** [comment]
Oops, needed to resync my tree with the official PCP tree.  Sorry.
