### ISSUE TITLE
pcp pidstat crashes on a pcp-zeroconf collected archive

### ISSUE THREAD

**Issue by mbaldessari** [performancecopilot/pcp#625]
I collected some archives on rhel8 beta via pcp-zeroconf. I am now trying to analyze it on my F30 laptop (pcp-4.3.1-2.fc30.x86_64):
$ pcp -a 20190330 pidstat -f '%y-%m-%d %H:%M:%S' -t30m -r > 0330-pistat.txt
Traceback (most recent call last):                                           
  File "/usr/libexec/pcp/bin/pcp-pidstat", line 916, in <module>             
    sts = manager.run()                                                      
  File "/usr/lib64/python3.7/site-packages/pcp/pmcc.py", line 665, in run    
    self._printer.report(self)                                               
  File "/usr/libexec/pcp/bin/pcp-pidstat", line 846, in report               
    ncpu = self.get_ncpu(group)                                              
  File "/usr/libexec/pcp/bin/pcp-pidstat", line 829, in get_ncpu             
    return group['hinv.ncpu'].netValues[0][2]                                
IndexError: list index out of range                                          

Archive is here: http://acksyn.org/files/tripleo/undercloud-0.redhat.local/

In this case it was the 20190330 one.

**Comment by mbaldessari** [comment]
So just to be more complete, it seems that when pmlogger was collecting the 20190330 archive, the system might have been under a lot of memory pressure and it might very well be that the OOM killer went on a spree and the archive might not have all the expected data
